<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Student;
use Carbon\Carbon;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $students = [
            [
                'application_number' => 'APP2025001',
                'admission_test_roll_no' => 'ATR2025001',
                'programme_name' => 'B.Tech Computer Science',
                'batch' => '2025',
                'student_id' => 'STU2025001',
                'section' => 'A',
                'first_name' => 'Amit',
                'last_name' => 'Sharma',
                'district' => 'Mumbai',
                'address' => '123, Andheri East, Mumbai, Maharashtra',
                'category' => 'Unreserved',
                'dob' => Carbon::parse('2003-04-15'),
                'gender' => 'Male',
                'email' => 'amit.sharma@example.com',
                'alternate_email' => null,
                'mobile' => '9876543210',
                'alternate_mobile' => null,
                'whatsapp' => '9876543210',
                'is_pwbd' => false,
                'occupation' => 'Student',
                'father_name' => 'Rakesh Sharma',
                'mother_name' => 'Sunita Sharma',
                'father_occupation' => 'Engineer',
                'mother_occupation' => 'Teacher',
                'family_income' => 1200000.00,
                'selection_type' => 'Merit',
                'score_A' => 85.50,
                'score_B' => 78.25,
                'score_C' => 92.00,
                'score_D' => 88.75,
                'status' => 'Active',
                'note' => 'Excellent academic performance',
                'remarks' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'application_number' => 'APP2025002',
                'admission_test_roll_no' => 'ATR2025002',
                'programme_name' => 'B.Sc Physics',
                'batch' => '2025',
                'student_id' => 'STU2025002',
                'section' => 'B',
                'first_name' => 'Priya',
                'last_name' => 'Verma',
                'district' => 'Delhi',
                'address' => '45, Rohini, Delhi',
                'category' => 'OBC',
                'dob' => Carbon::parse('2004-01-22'),
                'gender' => 'Female',
                'email' => 'priya.verma@example.com',
                'alternate_email' => 'priya.v@example.com',
                'mobile' => '8765432109',
                'alternate_mobile' => '7654321098',
                'whatsapp' => '8765432109',
                'is_pwbd' => false,
                'occupation' => 'Student',
                'father_name' => 'Vijay Verma',
                'mother_name' => 'Anita Verma',
                'father_occupation' => 'Businessman',
                'mother_occupation' => 'Homemaker',
                'family_income' => 800000.00,
                'selection_type' => 'Merit',
                'score_A' => 90.25,
                'score_B' => 85.00,
                'score_C' => 87.50,
                'score_D' => 91.00,
                'status' => 'Active',
                'note' => 'Strong in physics',
                'remarks' => 'Needs to improve attendance',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'application_number' => 'APP2025003',
                'admission_test_roll_no' => 'ATR2025003',
                'programme_name' => 'B.A Economics',
                'batch' => '2025',
                'student_id' => 'STU2025003',
                'section' => 'A',
                'first_name' => 'Rahul',
                'last_name' => 'Mehta',
                'district' => 'Jaipur',
                'address' => '78, Malviya Nagar, Jaipur, Rajasthan',
                'category' => 'SC',
                'dob' => Carbon::parse('2003-11-30'),
                'gender' => 'Male',
                'email' => 'rahul.mehta@example.com',
                'alternate_email' => null,
                'mobile' => '6543210987',
                'alternate_mobile' => null,
                'whatsapp' => '6543210987',
                'is_pwbd' => true,
                'occupation' => 'Student',
                'father_name' => 'Suresh Mehta',
                'mother_name' => 'Kavita Mehta',
                'father_occupation' => 'Government Employee',
                'mother_occupation' => 'Nurse',
                'family_income' => 600000.00,
                'selection_type' => 'Quota',
                'score_A' => 75.00,
                'score_B' => 70.50,
                'score_C' => 80.25,
                'score_D' => 78.00,
                'status' => 'Active',
                'note' => 'Eligible for PwBD benefits',
                'remarks' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'application_number' => 'APP2025004',
                'admission_test_roll_no' => 'ATR2025004',
                'programme_name' => 'B.Tech Mechanical',
                'batch' => '2025',
                'student_id' => 'STU2025004',
                'section' => 'C',
                'first_name' => 'Sneha',
                'last_name' => 'Patel',
                'district' => 'Ahmedabad',
                'address' => '12, Navrangpura, Ahmedabad, Gujarat',
                'category' => 'Unreserved',
                'dob' => Carbon::parse('2004-06-10'),
                'gender' => 'Female',
                'email' => 'sneha.patel@example.com',
                'alternate_email' => null,
                'mobile' => '5432109876',
                'alternate_mobile' => '4321098765',
                'whatsapp' => '5432109876',
                'is_pwbd' => false,
                'occupation' => 'Student',
                'father_name' => 'Mahesh Patel',
                'mother_name' => 'Rekha Patel',
                'father_occupation' => 'Doctor',
                'mother_occupation' => 'Homemaker',
                'family_income' => 1500000.00,
                'selection_type' => 'Merit',
                'score_A' => 88.75,
                'score_B' => 90.00,
                'score_C' => 85.50,
                'score_D' => 87.25,
                'status' => 'Pending',
                'note' => 'Good academic record',
                'remarks' => 'Awaiting document verification',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'application_number' => 'APP2025005',
                'admission_test_roll_no' => 'ATR2025005',
                'programme_name' => 'B.Sc Chemistry',
                'batch' => '2025',
                'student_id' => 'STU2025005',
                'section' => 'B',
                'first_name' => 'Vikram',
                'last_name' => 'Singh',
                'district' => 'Lucknow',
                'address' => '56, Gomti Nagar, Lucknow, Uttar Pradesh',
                'category' => 'ST',
                'dob' => Carbon::parse('2003-09-05'),
                'gender' => 'Male',
                'email' => 'vikram.singh@example.com',
                'alternate_email' => 'vikram.s@example.com',
                'mobile' => '3210987654',
                'alternate_mobile' => null,
                'whatsapp' => '3210987654',
                'is_pwbd' => false,
                'occupation' => 'Student',
                'father_name' => 'Rajesh Singh',
                'mother_name' => 'Meena Singh',
                'father_occupation' => 'Farmer',
                'mother_occupation' => 'Homemaker',
                'family_income' => 400000.00,
                'selection_type' => 'Quota',
                'score_A' => 80.00,
                'score_B' => 82.50,
                'score_C' => 78.75,
                'score_D' => 81.00,
                'status' => 'Active',
                'note' => 'Eligible for ST quota',
                'remarks' => null,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($students as $student) {
            Student::create($student);
        }
    }
}
